export const refs = {
  loginForm: document.querySelector(".js-login-form"),
  registerForm: document.querySelector(".js-register-form"),
  confirmForm: document.querySelector(".js-confirm-form"),
  confirmSection: document.querySelector(".js-confirm-section"),
  capsulaList: document.querySelector(".js-capsula-list"),
  capsulaModalDetails: document.querySelector(".js-modal"),
  capsulaModalBackdrop: document.querySelector(".js-backdrop"),
  prevButton: document.querySelector(".js-modal-prev"),
  nextButton: document.querySelector(".js-modal-next"),
  createCapsulaForm: document.querySelector(".js-create-capsula-form"),
  mapList: document.querySelector(".js-map"),
  loginBtn: document.querySelector(".js-login-button"),
  logoutBtn: document.querySelector(".js-logout-button"),
  loadBtn: document.querySelector(".js-load-btn"),
};
